### ISSUE TITLE
Todo refactor 2

### ISSUE THREAD

**Issue by marqueewinq** [Quadrocube/Pack-o-Morphs#2]
@IlyaGusev
# Тудушка для рефакторинга №2

Всё пиздец.
## core/hexagonfield.js
- [ ] - хранить [игроков](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L26) в другое место
- [x] - переделать [GenerateGrid](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L64)
- [x] - почему в [35](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L35) пополам при X, а в [68](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L68) при Y?
- [ ] - [hexField ](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L14)и [creatureField ](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L15)объявить словарём
- [ ] - переделать [Move](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L97)
- [ ] - почему в [Add](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L131) двигаем в [0,0]
- [ ] - [radius_with_blocks](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L135) недоступен здесь
- [ ] - кидать исключения в [подобных](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L210) случаях (прдумать еще)
- [ ] - оптимизировать [такие](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L262) такие case
- [ ] - сделать метод для [newCreature](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L279): объединить [new TFieldObject ](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L2) и [newCreature](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/gamelogic.js#L278)
## core/fieldobjects.js
- [ ] - переименовать [marker](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L19)
- [ ] - убрать [отрисовку](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L17) из TFieldObject; создать функцию, отрисовывающую спрайт отдельно
- [ ] - убрать [элемент коллекции добавляет сам себя](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L32)
- [ ] - перенести [OnDragStart](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L41), OnDragStop и спрайт в [hexagonfield.js](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js)
- [ ] - перенести [SetNewPosition](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L69) в [hexagonfield.js](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js)
- [ ] - перенести [MoveRange](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L103) в  [hexagonfield.js](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js)

В итоге должно остаться только данные 
- [ ] - убрать лишние аргументы [конструктора](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/fieldobject.js#L2)
## core/turnstate.js

Всё инфобары во владении turnstate.js
- [ ] - [field](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/turnstate.js#L72) -> fieldObject
- [ ] - [MyTurn](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/turnstate.js#L113) -> Upkeep
## core/gameworld.js
- [x] - Все расчёты позиции переместить сюда (подаём colrow, получаем x,y)
- [x] - Убрать game из [FindHex](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/gameworld.js#L41)
- [x] - [FieldPosX ](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/gameworld.js#L15) переименовать
- [x] - сделать нормальный двумерный массив вместо [этого](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/gameworld.js#L37)
## core/hex.js
- [ ] - [radius_with_blocks](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/hexagonfield.js#L135) сделать в единственном экземпляре
- [ ] - объединить с [gameworld.js](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/core/gameworld.js)
## global.js
- [ ] - сделать словари вместо этих [функций](https://github.com/marqueewinq/Pack-o-Morphs/blob/master/client/include/global.js#L90)
